services:
  postgres:
    image: postgres:16
    container_name: superfood-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: superfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - superfood-postgres-data:/var/lib/postgresql/data

volumes:
  superfood-postgres-data:
