<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>CS8669</NoWarn>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <PackageReference Include="MudBlazor" Version="9.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperFood.Contracts\SuperFood.Contracts.csproj" />
    <ProjectReference Include="..\SuperFood.Client.Shared\SuperFood.Client.Shared.csproj" />
  </ItemGroup>

</Project>
